#!/usr/bin/env bash
set -e

if [ -z "${1}" ]; then
    echo USAGE: ${0} WDL && exit 2
fi

wdl=$(realpath "${1}")
echo "WDL: ${wdl}"
if [ ! -s "${wdl}" ]; then
    echo Given WDL "${wdl}" does not exist! && exit 2
fi

import_wdls=($(grep import "${wdl}" | awk -F\" '{print $2}'))
if [ ${#import_wdls[*]} == 0 ]; then
    echo "WDL has no imports, skipping!"
    exit 0
fi

# Get the imports directory
wdl_dn=$(dirname "${wdl}")
echo "Directory: ${wdl}"
relative_dn=$(echo "${import_wdls[0]}" | awk -F/ '{print $1}')
imports_dn="${wdl_dn}"
while true; do
    cbn=$(basename "${imports_dn}")
    if test "${cbn}" == "${relative_dn}"; then
        break
    fi
    imports_dn=$(dirname "${imports_dn}")
done
imports_dn=$(dirname "${imports_dn}")
echo "Imports directory: ${imports_dn}"

# Copy imports to working dir for zipping
working_dn=$(mktemp -d 2>/dev/null || mktemp -d -t 'build-imports-XXX')
for import_wdl in $(grep import "${wdl}" | awk -F\" '{print $2}'); do
    import_wdl_fn="${imports_dn}/${import_wdl}"
    if [ ! -e ${import_wdl_fn} ]; then
        echo "Missing import [${import_wdl}], cannot build imports." 
        exit 1
    fi
    dest_bdn=$(dirname ${import_wdl})
    dest_dn="${working_dn}/${dest_bdn}"
    mkdir -p "${dest_dn}"
    cp "${import_wdl_fn}" ${dest_dn}
done

# Zip imports
cd ${working_dn}
zip_fn="${wdl/\.wdl/.imports.zip}"
zip -qr "${zip_fn}" .
unzip -l "${zip_fn}"
echo Created imports file: "${zip_fn}"

function cleanup() {
    rm -rf "${working_dn}"
}
trap cleanup EXIT

exit
